# 1

In [38]:
import numpy as np

column1 = [0.7, 0.4, -0.2, -0.4]
column2 = [-0.3, 0.5, 0.8, 0.3]
column3 = [0.8, 0.6, 0.3, 0.3]

X = np.column_stack((column1, column2))
y = np.array(column3)

X

array([[ 0.7, -0.3],
       [ 0.4,  0.5],
       [-0.2,  0.8],
       [-0.4,  0.3]])

### a)

In [39]:
# Regularization parameter (λ)
alpha = 0.1

# Define the RBF centers
centers = [(0, 0), (1, -1), (-1, 1)]

# Initialize an empty array for the transformed data
X_transformed = np.zeros((len(column1), len(centers)))

# Apply the radial basis function for each center
for j, center in enumerate(centers):
    for i in range(len(column1)):
        x = np.array([column1[i], column2[i]])
        c = np.array(center)
        # Compute the radial basis function value and store it in the transformed_data array
        X_transformed[i, j] = np.exp(-np.linalg.norm(x - c)**2 / 2)

print(X_transformed)

[[0.74826357 0.74826357 0.10126646]
 [0.81464732 0.27117254 0.33121088]
 [0.71177032 0.09632764 0.71177032]
 [0.8824969  0.16121764 0.65376979]]


Learn the Ridge regression (𝑙2 regularization) using the closed solution

In [40]:
np.matmul(X_transformed.T, X_transformed)

array([[2.50896639, 0.99164557, 1.42916086],
       [0.99164557, 0.66870305, 0.33955168],
       [1.42916086, 0.33955168, 1.05398747]])

In [41]:
np.matmul(X_transformed.T, X_transformed) + alpha * np.identity(3)

array([[2.60896639, 0.99164557, 1.42916086],
       [0.99164557, 0.76870305, 0.33955168],
       [1.42916086, 0.33955168, 1.15398747]])

In [42]:
inv = np.linalg.pinv(np.matmul(X_transformed.T, X_transformed) + alpha * np.identity(3))
inv


array([[ 2.84662423, -2.43092076, -2.81013512],
       [-2.43092076,  3.57115579,  1.9598002 ],
       [-2.81013512,  1.9598002 ,  3.77012906]])

In [43]:
moore_penrose = np.matmul(inv, X_transformed.T)
moore_penrose

array([[ 0.02648332,  0.72904851, -0.20819299,  0.28304831],
       [ 1.05165836, -0.36283655,  0.00867137, -0.28828856],
       [-0.25448701, -0.50911727,  0.87207812,  0.3008153 ]])

In [44]:
W_ridge = np.matmul(moore_penrose, y)
W_ridge

array([ 0.48107235,  0.5397396 , -0.15719195])

Normal Regression

In [47]:
W = np.matmul(np.matmul(np.linalg.inv(np.matmul(X_transformed.T, X_transformed)), X_transformed.T), y)
W

array([ 0.68169736,  0.45474315, -0.41676232])

### b)

In [46]:
y_pred = np.dot(X_transformed, W_ridge)

rmse = np.sqrt(np.mean((y - y_pred)**2))

print("RMSE:", rmse)

RMSE: 0.08337222225062338
