# 1

In [82]:
import numpy as np

column1 = [0.7, 0.4, -0.2, -0.4]
column2 = [-0.3, 0.5, 0.8, 0.3]
column3 = [0.8, 0.6, 0.3, 0.3]

X = np.column_stack((column1, column2))

y = np.array(column3)

X

array([[ 0.7, -0.3],
       [ 0.4,  0.5],
       [-0.2,  0.8],
       [-0.4,  0.3]])

### a)

In [83]:
# Regularization parameter (λ)
alpha = 0.1

# Define the RBF centers
centers = [(0, 0), (1, -1), (-1, 1)]

# Initialize an empty array for the transformed data
X_transformed = np.zeros((len(column1), len(centers)))

# Apply the radial basis function for each center
for j, center in enumerate(centers):
    for i in range(len(column1)):
        x = np.array([column1[i], column2[i]])
        c = np.array(center)
        # Compute the radial basis function value and store it in the transformed_data array
        X_transformed[i, j] = np.exp(-np.linalg.norm(x - c)**2 / 2)

# Add a column of 1s for the bias term
bias_column = np.ones((len(column1), 1))
X_transformed = np.hstack((bias_column, X_transformed))

print(X_transformed)

[[1.         0.74826357 0.74826357 0.10126646]
 [1.         0.81464732 0.27117254 0.33121088]
 [1.         0.71177032 0.09632764 0.71177032]
 [1.         0.8824969  0.16121764 0.65376979]]


Learn the Ridge regression (𝑙2 regularization) using the closed solution

In [84]:
np.matmul(X_transformed.T, X_transformed)

array([[4.        , 3.15717811, 1.27698138, 1.79801745],
       [3.15717811, 2.50896639, 0.99164557, 1.42916086],
       [1.27698138, 0.99164557, 0.66870305, 0.33955168],
       [1.79801745, 1.42916086, 0.33955168, 1.05398747]])

In [85]:
np.matmul(X_transformed.T, X_transformed) + alpha * np.identity(4)

array([[4.1       , 3.15717811, 1.27698138, 1.79801745],
       [3.15717811, 2.60896639, 0.99164557, 1.42916086],
       [1.27698138, 0.99164557, 0.76870305, 0.33955168],
       [1.79801745, 1.42916086, 0.33955168, 1.15398747]])

In [86]:
inv = np.linalg.pinv(np.matmul(X_transformed.T, X_transformed) + alpha * np.identity(4))
inv


array([[ 4.54826202, -3.77681832, -1.86116983, -1.86155421],
       [-3.77681832,  5.98284561, -0.88542926, -1.26432443],
       [-1.86116983, -0.88542926,  4.33275508,  2.72155678],
       [-1.86155421, -1.26432443,  2.72155678,  4.53204296]])

In [87]:
moore_penrose = np.matmul(inv, X_transformed.T)
moore_penrose

array([[ 0.14104789,  0.35022196,  0.3557537 , -0.30184975],
       [-0.09064104,  0.43822869, -0.50360629,  0.53370047],
       [ 0.99394091, -0.506149  , -0.13690469, -0.16477025],
       [-0.31221638, -0.65245932,  0.726472  ,  0.42435912]])

In [88]:
W_ridge = np.matmul(moore_penrose, y)
W_ridge

array([ 0.33914267,  0.19945264,  0.40096085, -0.29599936])

Normal Regression

In [89]:
W = np.matmul(np.matmul(np.linalg.inv(np.matmul(X_transformed.T, X_transformed)), X_transformed.T), y)
W

array([ 1.1372652 , -0.283163  , -0.04756383, -0.88671365])

### b)

In [92]:
y_pred = np.dot(X_transformed, W_ridge)

rmse = np.sqrt(np.mean((y - y_pred)**2))

print("RMSE:", rmse)

RMSE: 0.06508238153393446


# 2